/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jappsemana11;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class jFrmInternalClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form jFrmInternalClientes
     */
    public jFrmInternalClientes() {
        initComponents();
    }
    
    void LimpiarControles(){
        TxtIdeCliente.setText("");
        TxtNomCliente.setText("");
        CmbTipoCliente.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        TxtCliente = new javax.swing.JTextField();
        BtnCliente = new javax.swing.JButton();
        TxtIdeCliente = new javax.swing.JTextField();
        TxtNomCliente = new javax.swing.JTextField();
        CmbTipoCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Gestion Clientes");

        BtnRegistrar.setText("Registrar venta");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        BtnCliente.setText("Registrar cliente");
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });

        CmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Normal" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtIdeCliente)
                            .addComponent(TxtNomCliente)
                            .addComponent(CmbTipoCliente, 0, 157, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistrar)
                    .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(BtnCliente)
                .addGap(18, 18, 18)
                .addComponent(TxtIdeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String NomCliente = TxtCliente.getText();
        Main.ListaVentas.add(NomCliente);
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
        
        try {
             Cliente oCliente = new Cliente();
            oCliente.IdeCliente = TxtIdeCliente.getText();
            oCliente.NomCliente = TxtNomCliente.getText();
            oCliente.TipoCliente = CmbTipoCliente.getSelectedIndex() == 0 ? 'V' : 'N';
            Main.ListadoClientes.add(oCliente);
            LimpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
       
    }//GEN-LAST:event_BtnClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCliente;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CmbTipoCliente;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JTextField TxtIdeCliente;
    private javax.swing.JTextField TxtNomCliente;
    // End of variables declaration//GEN-END:variables
}
