/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package japplicationb;

import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFrmVentasSuperiores extends javax.swing.JInternalFrame {

    DefaultListModel listaVentasSuperiores;
    
    /**
     * Creates new form JFrmVentasSuperiores
     */
    public JFrmVentasSuperiores() {
        initComponents();
        listaVentasSuperiores = new DefaultListModel();
        LstVentas.setModel(listaVentasSuperiores);
    }
    
    String BuscarCliente(String IdCliente){
        
        
        String NombreCliente = "";
         Cliente aux = new Cliente();
        int posicion = -1;
        
        for (int i = 0; i < Main.ListadoClientes.size(); i++) {
            
            if (Main.ListadoClientes.get(i).getIdeCliente().equals(IdCliente.trim())){
                posicion = i;
                break;
            }
        }
        
       if (posicion >= 0){
         aux = Main.ListadoClientes.get(posicion);                 
       }      
       
       return aux.getNomCliente();   
    }
    
    Double ObtenerTotal(ArrayList<DetalleVenta> listaVenta){
        
        Double TotalVenta = 0.00 ;
        
        for (DetalleVenta detalleVenta : listaVenta) {
            TotalVenta += detalleVenta.getSubTotal();
        }
        
        return TotalVenta;
        
    }
    
    
     void CargarVentasHechas(){
        
        try {
            
            String IdeCliente = "";
            String NomCliente = "";
            ArrayList<DetalleVenta> ListaFiltrada = new ArrayList<DetalleVenta>();
            
            for (int i = 1; i <= Main.IdVenta; i++) {
                
                int IdVenta = i;
                
                char TipoCliente = cmbTipoCliente.getSelectedIndex() == 0 ? 'N' :'E';
                
                ListaFiltrada = (ArrayList<DetalleVenta>)Main.ListaDetalleVentaGuardada.stream()
                                                .filter(dVenta -> dVenta.getIdVenta() == IdVenta && dVenta.getTipoCliente() == TipoCliente)
                                                .collect(Collectors.toList());
               
                
                //Se obtiene el IdCliente y su nombre
                for (DetalleVenta oDetalleVenta : ListaFiltrada) {
                    IdeCliente = oDetalleVenta.getIdeCliente();
                    NomCliente = BuscarCliente(oDetalleVenta.getIdeCliente());
                    break;
                
                }
                
                if (ListaFiltrada.isEmpty()){
                    continue;
                }
                        
                
                Double TotalVenta = ObtenerTotal(ListaFiltrada);
                String leyenda = String.format("La venta con Id %d del cliente %s con cedula %s fue de un total de %.2f dolares", IdVenta,NomCliente,IdeCliente,TotalVenta);                
                
                if (TxtMontoSuperior.getText().isBlank()){
                      
                     listaVentasSuperiores.addElement(leyenda);
                }else{
                    
                    if (TotalVenta >= Double.parseDouble(TxtMontoSuperior.getText())){
                        listaVentasSuperiores.addElement(leyenda);
                    }
                   
                }
                
                
                
                
            }
            
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error registro cliente "+
                                        e.getMessage()+" "+
                                        e.getStackTrace()[0].toString());
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LstVentas = new javax.swing.JList<>();
        BtnObtener = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtMontoSuperior = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Filtro de Ventas");

        jScrollPane1.setViewportView(LstVentas);

        BtnObtener.setText("Obtener");
        BtnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnObtenerActionPerformed(evt);
            }
        });

        jLabel1.setText("Venta superior a");

        jLabel2.setText("Tipo Cliente");

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Extranjero" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnObtener)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtMontoSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtMontoSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnObtener)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnObtenerActionPerformed
        listaVentasSuperiores = new DefaultListModel();
        LstVentas.setModel(listaVentasSuperiores);
        CargarVentasHechas();
    }//GEN-LAST:event_BtnObtenerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnObtener;
    private javax.swing.JList<String> LstVentas;
    private javax.swing.JTextField TxtMontoSuperior;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
