/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package japplicationb;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrmCliente
     */
    public JFrmCliente() {
        initComponents();
        InicializarControles();
        
    }
    
    
    
    void InicializarControles(){
        TxtIdeCliente.setText("");
        TxtNomCliente.setText("");
        CmbTipoCliente.setSelectedIndex(0);
        TxtIdeCliente.setFocusable(true);
    }
    
    void RegistrarCliente(){
        try {
            int impuestoVenta = 1; //simulando que si se determino IVA
            
            if (impuestoVenta == 0){
                throw new Exception("No se calculo bien IVA de venta");
            }
            
            Cliente oCliente = new Cliente();
            oCliente.setIdeCliente(TxtIdeCliente.getText());
            oCliente.setNomCliente(TxtNomCliente.getText());
            char TipoCliente = CmbTipoCliente.getSelectedIndex() == 0 ? 'V' : 'N';
            oCliente.setTipoCliente(TipoCliente);
            Main.ListadoClientes.add(oCliente);
            JOptionPane.showMessageDialog(null,"Cliente registrado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error registro cliente "+
                                        e.getMessage()+" "+
                                        e.getStackTrace()[0].toString()
                    );
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrarCliente = new javax.swing.JButton();
        TxtIdeCliente = new javax.swing.JTextField();
        TxtNomCliente = new javax.swing.JTextField();
        CmbTipoCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Gestion Clientes");

        BtnRegistrarCliente.setText("Registrar Cliente");
        BtnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarClienteActionPerformed(evt);
            }
        });

        CmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Normal" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(TxtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BtnRegistrarCliente)
                .addGap(28, 28, 28)
                .addComponent(TxtIdeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(CmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(TxtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarClienteActionPerformed
       RegistrarCliente(); 
       InicializarControles();
        
    }//GEN-LAST:event_BtnRegistrarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarCliente;
    private javax.swing.JComboBox<String> CmbTipoCliente;
    private javax.swing.JTextField TxtIdeCliente;
    private javax.swing.JTextField TxtNomCliente;
    // End of variables declaration//GEN-END:variables
}
